# Python Tutorial
## Second Header 

Git Help:
https://www.geeksforgeeks.org/top-12-most-used-git-commands-for-developers/

Quick Advice:
If python doesnt work after creating the .jupyter notebook file you just have to download it again and click in the upper right 
on the python version. If it is downloaded correctly it should recognise it

Shortcut: 
* New cell below = b
* New cell above = a
* Markdown = m
* Delete = dd / delete key
* Press SHIFT TAB to see what the function does in a notebook

Date: 27/05/2024 & 28/05/2024

Part 1: Start with Jupyter Notebook & Learn Basics Syntax

**Topics**
* Basic Arithmetic Operations
* Control and Conditional Structures
* Looping - for, while loops
* User Input
* Strings
* Integers
* Floating Values
* Typecasting 


## Basic Arithmetic Operations
Addition	x + y

Subtraction	x - y

Multiplication	x * y

Division	x / y

Modulus	x % y

Exponentiation	x ** y

Floor division	x // y


In [2]:
1+1

2

In [3]:
10-2

8

In [4]:
5*5

25

In [10]:
10 * "str"

'strstrstrstrstrstrstrstrstrstr'

In [5]:
5/2

2.5

In [6]:
3%2

1

In [7]:
3**3

27

In [12]:
5//2
print("it gets rounded down")

it gets rounded down


## Inbuilt Function


In [13]:
type(1)

int

In [14]:
type("hello")

str

In [15]:
type(True)

bool

## Variable Assignment

In [22]:
a = 10

In [24]:
type(a)

int

In [25]:
a = "Paolo Alberda"

In [26]:
type(a)

str

## Mathematical Operations

In [27]:
a = 10
b = 20

In [28]:
print(a*b)
print(a/b)
print(a%b)
print((a*b)+(a/b))

200
0.5
10
200.5


## Various Ways of Printing

In [30]:
first_name = 'Paolo'
last_name = 'Alberda'

In [32]:
print("My first name is {} and last name is {}".format(first_name,last_name))

My first name is Paolo and last name is Alberda


In [35]:
print("My first name is {first} and last name is {last}".format(first=first_name,last=last_name))

My first name is Paolo and last name is Alberda


In [36]:
len('alberda')

7

In [37]:
type(1.0)

float

In [38]:
type('Paolo Alberda')

str

In [39]:
type(['1',2,3,4.5])

list

## Control and Conditional Structures
* Simple if-statement
* If-else statement
* If-elif-else statement
* Nested if statement

Write a Python program to convert temperatures to and from Celsius and Fahrenheit.

In [49]:
input_a = input("Do you know the degrees in Celcius?")
if input_a == 'yes':
    c = int(input("give me the temperature in Celsius"))
    answer_c = (c * (9/5) + 32)
    print("{c} degrees celcius is {answer_c} Fahrenheit".format(c=c,answer_c=answer_c))
else:
    input_b = input("Do you know the degrees in Fahrenheit?")
    f = int(input("give me the temperature in Celsius"))
    answer_f = (f - 32) * (5/9)
    print("{f} degrees Fahrenheit is {answer_f} Celsius".format(f=f,answer_f=answer_f))

999 degrees Fahrenheit is 537.2222222222223 Celsius


## Lists

In [50]:
list_practice = ['Math','Chemistry',100,200,300,400]

In [51]:
list_practice

['Math', 'Chemistry', 100, 200, 300, 400]

In [53]:
list_practice.append('Paolo')

In [55]:
list_practice

['Math', 'Chemistry', 100, 200, 300, 400, 'Paolo']

In [56]:
list[:]

list[slice(None, None, None)]

In [60]:
list_practice[1:]

['Chemistry', 100, 200, 300, 400, 'Paolo']

In [61]:
list_practice[:4]

['Math', 'Chemistry', 100, 200]

In [62]:
list_practice.insert(0,"alberda")

In [64]:
list_practice

['alberda', 'Math', 'Chemistry', 100, 200, 300, 400, 'Paolo']

In [65]:
list_practice.append(["A","B"])

In [66]:
list_practice

['alberda', 'Math', 'Chemistry', 100, 200, 300, 400, 'Paolo', ['A', 'B']]

Extend Method

In [67]:
list_new = [1,2,3,4,5]

In [68]:
list_new.extend([8,9])

In [69]:
list_new

[1, 2, 3, 4, 5, 8, 9]

In [70]:
sum(list_new)

32

In [71]:
list_new.pop(0)

1

In [72]:
list_new

[2, 3, 4, 5, 8, 9]

Counts

In [73]:
lst = [1,1,2,3,4,5]
lst.count(1)

2

In [74]:
len(lst)

6

In [80]:
lst.index(3,0,6) # that number 3 is on index 3

3

In [82]:
lst.index(1,0,6) # that number 1 is on index 0

0

## Sets

In [89]:
set = {"A","B","C"}

In [90]:
type(set)

set

## Dictionary

In [91]:
dict = {}

In [92]:
type(dict)

dict

In [93]:
my_dict ={"Car1":"Audi","Car2":"BMW","Car3":"Peugot"}

In [94]:
my_dict["Car1"]

'Audi'

In [95]:
for x in my_dict.values():
    print(x)

Audi
BMW
Peugot


In [97]:
for x in my_dict.items():
    print(x)

('Car1', 'Audi')
('Car2', 'BMW')
('Car3', 'Peugot')


In [99]:
my_dict['Car4']='Audi 2.0'

In [100]:
my_dict

{'Car1': 'Audi', 'Car2': 'BMW', 'Car3': 'Peugot', 'Car4': 'Audi 2.0'}

In [102]:
car1_model = {'Mercedes':1960}
car2_model = {'Audi':1970}
car3_model = {'Ambassador':1980}

car_type={'car1':car1_model,'car2':car2_model,'car3':car3_model}

In [103]:
print(car_type)

{'car1': {'Mercedes': 1960}, 'car2': {'Audi': 1970}, 'car3': {'Ambassador': 1980}}


In [104]:
print(car_type['car1'])

{'Mercedes': 1960}


In [105]:
print(car_type['car1']['Mercedes'])

1960


## Tuple
* Is immutable
* where the definition of an item is only required for one time

In [106]:
my_tuple=("Krish","Ankur","John")

In [108]:
my_tuple.index('John')

2

## Numpy Tutorial

In [4]:
import numpy as np

In [26]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,6,5,4]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [27]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 5, 4]])

In [6]:
arr.shape

(3, 5)

In [12]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 5, 4]])

In [15]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 5, 4]])

In [17]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [18]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [28]:
arr1=arr.copy()

In [29]:
print(arr)
arr1[3:]=1000
print(arr1)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 5 4]]
[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 5 4]]


## Pandas

In [34]:
import pandas as pd
import numpy as np

In [36]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=["Column1","Column2","Column3","Column4"])

In [42]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [44]:
df.to_csv('Test.csv')

Accessing the Elements
1. .loc option = 1
2. .iloc option = when more than 1

In [45]:
df.loc['Row1']

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int32

In [46]:
type(df.loc['Row1'])

pandas.core.series.Series

In [47]:
df.iloc[0:2,0:2] #Python starts at index 0

Column1  Column2
Row1        0        1
Row2        4        5

In [49]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [53]:
df[['Column1','Column2']]

Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row5       16       17

In [48]:
df['Column1'].value_counts()

Column1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

## Reading CSV files With Various Parameters

In [ ]:
#URL to csv
dff=pd.read_csv('https://downloadxxxxxxxxxxxxxxLINKLINKLINKEXAMPLE',step='\t')

## Pandas-Reading JSON,Reading HTML, Read PICKLE, Read EXCEL Files